name: CI/CD

on:
  push:
    branches: ['**']
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  checks: write        # required by dorny/test-reporter

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Unit Tests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Unit Tests
        shell: pwsh
        run: |
          test/!RunAllTests.ps1 -folder '${{ github.workspace }}/' -TestFilenameFilter "*" -InstallModules:$false -ResultOutputFormat "JUnitXml"

      - name: Publish Test Results
        uses: dorny/test-reporter@v3
        if: ${{ !cancelled() }}
        with:
          name: Pester Tests
          path: '**/TEST-*.xml'
          reporter: java-junit
          collapsed: 'auto'

  publish:
    name: Publish to PS Gallery
    runs-on: windows-latest
    needs: test
    if: ${{ github.event_name != 'pull_request' }}

    steps:
      - uses: actions/checkout@v4

      - name: Publish module to PowerShell Gallery
        shell: pwsh
        env:
          PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
        run: |
          $isPreview = '${{ github.ref_name }}' -ne 'master'
          Write-Host "Branch: ${{ github.ref_name }} | Preview: $isPreview"
          ./tools/Publish-ToGallery.ps1 -IsPreview:$isPreview -NuGetApiKey $env:PSGALLERY_API_KEY
