name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

permissions:
  contents: read
  checks: write        # required by test-reporter

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6

    - name: Login via Az module
      uses: azure/login@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Run All Unit and Integration Tests
      uses: azure/powershell@v3
      with:
        inlineScript: |
          test/!RunAllTests.ps1 -folder '${{ github.workspace }}/' -TestFilenameFilter "Get*" -InstallModules:$false -ResultOutputFormat "JUnitXml"
        azPSVersion: "latest"

    - name: Publish Pester Test Results
      uses: dorny/test-reporter@v3
      if: ${{ !cancelled() }}           # run this step even if previous step failed
      with:
        name: Pester Tests
        path: '**/TEST-*.xml'
        reporter: java-junit
        collapsed: 'auto'
